#### Config for farmoni PoC ####

# Infos of etcd server
etcdserverport: "129.254.175.43:2379"

## Config for AWS ##
aws:

# Infos of Region
  region: ap-northeast-2
# Infos for creating Instnaces
  imageid: ami-047f7b46bd6dd5d84 
  instancenameprefix: awspowerkim  # EC2's Tag Name for group instances' ID
  instancetype: t2.micro
  securitygroupid: sg-2334584f
  subnetid: subnet-8c4a53e4
# for VM
  username: ec2-user
  keyname: aws.powerkim.keypair
  keyfilepath: /root/.aws/awspowerkimkeypair.pem 


## Config for GCP ##
gcp:

# for credential
  credentialfile: /root/.gcp/credentials
# Infos of Region
  region: us-east1
  zone: us-east1-c
# Project & Prefix for GCP
  projectid: ornate-course-236606
  prefix: https://www.googleapis.com/compute/v1/projects/ornate-course-236606
# Infos for creating Instnaces
  imageid: projects/gce-uefi-images/global/images/centos-7-v20190326
  instancenameprefix: gcepowerkim
  instancetype: https://www.googleapis.com/compute/v1/projects/ornate-course-236606/zones/us-east1-c/machineTypes/f1-micro
  subnetid: https://www.googleapis.com/compute/v1/projects/ornate-course-236606/regions/us-east1/subnetworks/default
  networkname: https://www.googleapis.com/compute/v1/projects/ornate-course-236606/global/networks/default
  serviceAccoutsMail: default
# for VM
  username: byoungseob
  keyname: empty
  keyfilepath: /root/.gcp/gcppowerkimkeypair.pem 



## Config for AZURE ##
azure:

# for credential
  credentialfile: /root/.azure/credentials

  groupname: VMGroupName
  location: westus2
  virtualnetworkname: virtualNetworkName
  subnet1name: subnet1Name
  subnet2name: subnet2Name
  networksecuritygroupname: nsgName
#  ipname: "ipName"
#  nicname: "nicName"

  basename: azurepowerkim
  username: powerkim
  password: powerkim
  keyfilepath: /root/.azure/azurepowerkimkeypair.pem
  publickeyfilepath: /root/.azure/azurepublickey.pem


